In [1]:
import numpy as np

# The Basics

In [2]:
# Initializing Numpy Array

a = np.array([1,2,3])
print(a) 

[1 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [51]:
# Get the Dimension
a.ndim

2

In [52]:
b.ndim

3

In [6]:
# Get Shape

b.shape

(2, 3)

In [7]:
# Get Data Type
a.dtype

dtype('int64')

In [8]:
a = np.array([1,2,3], dtype='int16')
a.dtype

dtype('int16')

In [9]:
# Get Size
a.itemsize

2

In [10]:
a = np.array([1,2,3], dtype='int32')
a.itemsize

4

In [11]:
# Get total size
a.nbytes

12

In [12]:
# Get number of elements
a.size

3

In [13]:
# Accessing/Changing specific elements, rows, columns, etc

In [38]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape

(2, 7)

In [20]:
# To get a specific element[r,c]
a[1, 5]

13

In [22]:
a[1, -2]

13

In [23]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# Get a spacific column
a[:, 2]

array([ 3, 10])

In [39]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [40]:
# Changing a element value

print(a)

a[1,5] = 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [43]:
a[1, 5] = 20

a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3-D Example

In [50]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [53]:
# Get specific element (work outside in)
b[0,1,1]

4

In [56]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [58]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [63]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [62]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [67]:
# Any other number
np.full((2,2), 91)

array([[91, 91],
       [91, 91]])

In [68]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [70]:
np.full((2,3), 99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [71]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [72]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [73]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.12977996, 0.96556342],
       [0.42000537, 0.18264295],
       [0.71370839, 0.94329876],
       [0.71495953, 0.90375169]])

In [74]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-4,  1,  7],
       [ 2,  3,  0],
       [ 1, -1,  0]])