In [1]:
import numpy as np

### The Basics

In [2]:
# Initializing Numpy Array

a = np.array([1,2,3])
print(a) 

[1 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get the Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape

b.shape

(2, 3)

In [8]:
# Get Data Type
a.dtype

dtype('int64')

In [9]:
a = np.array([1,2,3], dtype='int16')
a.dtype

dtype('int16')

In [10]:
# Get Size
a.itemsize

2

In [11]:
a = np.array([1,2,3], dtype='int32')
a.itemsize

4

In [12]:
# Get total size
a.nbytes

12

In [13]:
# Get number of elements
a.size

3

In [14]:
# Accessing/Changing specific elements, rows, columns, etc

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a.shape

(2, 7)

In [17]:
# To get a specific element[r,c]
a[1, 5]

13

In [18]:
a[1, -2]

13

In [19]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a spacific column
a[:, 2]

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
# Changing a element value

print(a)

a[1,5] = 20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [23]:
a[1, 5] = 20

a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-D Example

In [24]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [25]:
# Get specific element (work outside in)
b[0,1,1]

4

In [26]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays

In [27]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
# All 1s matrix
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [31]:
# All 1s matrix
np.ones((3,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [32]:
# Any other number
np.full((2,2), 91)

array([[91, 91],
       [91, 91]])

In [33]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [34]:
np.full((2,3), 99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [35]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [36]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal numbers
np.random.rand(3,2)

array([[0.20912281, 0.08121562],
       [0.77311844, 0.59116682],
       [0.96784306, 0.83429567]])

In [38]:
c = np.random.rand(4,2,3)
c.ndim

3

In [39]:
np.random.random_sample(a.shape)

array([[0.04226746, 0.38616068, 0.66527849, 0.77038134, 0.36726416,
        0.26995753, 0.1704382 ],
       [0.48702961, 0.47965157, 0.96882922, 0.40210673, 0.70286202,
        0.1013833 , 0.88944509]])

In [40]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[6, 4, 3],
       [2, 4, 0],
       [2, 1, 1]])

In [41]:
np.random.randint(-4,7, size=(3,3))

array([[-1,  3, -1],
       [-2,  2, -3],
       [ 0,  4, -2]])

In [42]:
# Identity metrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
# The identity metrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)   #Repeting 3 times to the array
print(r1)

[1 1 1 2 2 2 3 3 3]


In [45]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)   #Repeting 3 times to the array
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [46]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)   #Repeting 3 times to the array
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be carefull while copying arrays!!!

In [48]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [49]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [50]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [51]:
a + 2

array([3, 4, 5, 6])

In [52]:
a - 2

array([-1,  0,  1,  2])

In [53]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [54]:
a += 2
print(a)

[3 4 5 6]


In [55]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [56]:
a ** 2

array([ 9, 16, 25, 36])

In [57]:
# Take the sin
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [58]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [59]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [60]:
np.tan(a)

array([-0.14254654,  1.15782128, -3.38051501, -0.29100619])

### Linear Algebra

In [61]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [62]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [63]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.min(stats)

1

In [65]:
np.max(stats)

6

In [66]:
np.max(stats, axis=0)

array([4, 5, 6])

In [67]:
np.max(stats, axis=1)

array([3, 6])

In [68]:
np.sum(stats)

21

In [69]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [70]:
np.median(stats)

3.5

### Reorganizing Arrays

In [71]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [72]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from File

In [75]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing

In [76]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])